const WIDTH = 800;
const HEIGHT = 700;

const CARD_WIDTH = 334;
const CARD_HEIGHT = 440;
const CARD_SCALE = 0.13;
const CARD_SCALE_WIDTH = CARD_WIDTH * CARD_SCALE;
const CARD_SCALE_HEIGHT = CARD_HEIGHT * CARD_SCALE;
